# WallPanel
 # Battery charging status
binary_sensor:
  - name: "WallPanel Ładowanie"
    state_topic: "wallpanel/mywallpanel/sensor/battery"
    value_template: '{{ value_json.charging }}'
    payload_on: true
    payload_off: false
    device_class: battery_charging

 # Battery level
sensor:
  - name: "WallPanel Poziom baterii"
    state_topic: "wallpanel/mywallpanel/sensor/battery"
    unit_of_measurement: "%"
    value_template: "{{ value_json.value }}"
    device_class: battery
