# Data, czas oraz data+czas
- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_iso"

# Powiadomienia o stanie dysku backup zNAS
- platform: imap_email_content
  server: imap.gmail.com
  port: 993
  name: "BackupHDD Status"
  username: !secret home_assistant_dom_login
  password: !secret home_assistant_dom_password
  senders:
    - !secret qnap_mail
  value_template: >
    {% if '[Storage & Snapshots] Ejected external device \"ASMT 2115\"' in body %}
      Eject
    {% else %}
      Wait
    {% endif %}