# id adding template: RRRRmmDDhhMMss

# Wyłącz przy wyjściu z mieszkania
- id: "20211222100329"
  alias: "AWAY Wyłącz"
  trigger:
    - platform: state
      entity_id: 
        - alarm_control_panel.dom_2
      to:
        - "armed_away"
        - "armed_vacation"
  condition:
    condition: numeric_state
    entity_id: sensor.home_assistant_online_time
    above: 5
  action:
    - service: script.onkyo_off
    - service: switch.turn_off
      target:
        entity_id: switch.light_switch_corridor
    - service: switch.turn_off
      target:
        entity_id: light.light_dimmer_balcony
    - service: switch.turn_off
      target:
        entity_id: switch.light_fan_switch_kitchen_l1
    - service: switch.turn_off
      target:
        entity_id: switch.light_switch_storage_l1
    - service: switch.turn_off
      target:
        entity_id: switch.light_switch_sypialnia_2_l1

# Zarządzeniem ładowania tabletu
- id: "20211222100313"
  alias: "Zarządzanie ładowaniem tabletu WallPanel"
  description: Ładowanie tabletu na podstawie stanu baterii
  use_blueprint:
    path: homeassistant/battery_charging_on-off.yaml
    input:
      discharged_percent: '30'
      switch: switch.gniazdko_tablet_wallpanel
      phone_battery: sensor.wallpanel_poziom_baterii

# Włącz/Wyłącz choinkę przy wyjściu z mieszkania
- id: "20211222100341"
  alias: "CHRISTMAS Włącz/Wyłącz choinkę"
  mode: single
  trigger:
    - platform: state
      entity_id: alarm_control_panel.dom_2
      to:
        - "armed_away"
        - "armed_vacation"
        - "armed_night"
      id: "OFF"
    - platform: state
      entity_id: alarm_control_panel.dom_2
      to: "disarmed"
      id: "ON"
  condition:
    condition: numeric_state
    entity_id: sensor.home_assistant_online_time
    above: 5
  action:
  - choose:
      - conditions:
          - condition: trigger
            id: "OFF"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.gniazdko_keemple
      - conditions:
          - condition: trigger
            id: "ON"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: switch.gniazdko_keemple

# Dezaktywuje aktualizacją mapy odkurzacza gdy jest w bazie
- id: "20211222100418"
  alias: "ROBOROCK Camera off when docked"
  mode: restart
  trigger:
    - platform: state
      entity_id: vacuum.czesio
  condition:
    condition: template
    value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
    - service_template: >
        {% if trigger.to_state.state in ['unavailable', 'unknown', 'docked'] %}
          camera.turn_off
        {% else %}
          camera.turn_on
        {% endif %}
      entity_id: camera.xiaomi_cloud_map_extractor

# Ustawienie głośności na amplitunarze Onkyo TX-NR656
- id: "20220313110915"
  alias: "Onkyo TX-NR656 Volume Set"
  mode: restart
  trigger:
    - platform: state
      entity_id: input_number.onkyo_tx_nr656_volume_db
  condition:
    condition: template
    value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
    - service: media_player.volume_set
      target:
        entity_id: media_player.onkyo_tx_nr656
      data_template:
        volume_level: "{{ ( trigger.to_state.state | int(0) ) / 80 }}"

# Wyłącz amplituner przy wyłączeniu tv
- id: "20220424113705"
  alias: "Wyłącz amplituner przy wyłączeniu TV"
  trigger:
    - platform: state
      entity_id: media_player.tv_salon
      to: "off"
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.home_assistant_online_time
        above: 5
      - condition: template
        value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
      - condition: template
        value_template: "{{ is_state('media_player.onkyo_tx_nr656', 'on') }}"
  action:
    - service: script.onkyo_off

# Włącz/Wyłącz nawilżacz
- id: "202302181522"
  alias: "HUMIDITYFIER Włącz/Wyłącz nawilżacz Smartmi"
  mode: single
  trigger:
  - platform: state
    entity_id: schedule.smartmi_airhumidityfier_schedule
    to: "on"
    id: "ON"
  - platform: state
    entity_id: schedule.smartmi_airhumidityfier_schedule
    to: "off"
    id: "OFF"
  condition:
    condition: numeric_state
    entity_id: sensor.home_assistant_online_time
    above: 5
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: "ON"
      sequence:
      - if:
        - or:
          - not:
            - condition: state
              entity_id: alarm_control_panel.dom_2
              state: "armed_vacation"
          - and:
            - condition: state
              entity_id: alarm_control_panel.dom_2
              state: armed_vacation
            - condition: template
              value_template: "{{ states('sensor.date') == states('input_datetime.automation_heating_date_restore') }}"
        then:
        - service: humidifier.turn_on
          target:
            entity_id: humidifier.smartmi_pure_evaporative_air_humidifier
    - conditions:
      - condition: trigger
        id: "OFF"
      sequence:
      - service: humidifier.turn_off
        target:
          entity_id: humidifier.smartmi_pure_evaporative_air_humidifier

# Czesio - automatyczne odkurzanie
- id: "20230221053430"
  alias: "ROBOROCK full house cleaning"
  mode: single
  trigger:
    - platform: state
      entity_id: alarm_control_panel.dom_2
      to: 
      - "armed_vacation"
      - "armed_away"
  condition:
  - condition: numeric_state
    entity_id: sensor.home_assistant_online_time
    above: 5
  - condition: template
    value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  - not:
    - condition: state
      entity_id: script.roborock_hoovering
      state: "on"
  - condition: template
    value_template: "{{ states('sensor.czesio_last_full_apartment_cleaning') | int(100) > 72 }}"
  action:
  - parallel:
    - service: script.roborock_hoovering
    - sequence:
      - delay:
          seconds: 15
      - service: notify.telegram_zollek
        data:
          message: "Czesio - sprzątanie całego mieszkania"